# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=30, unique=True, verbose_name='Заголовок на русском языке')),
                ('title_en', models.CharField(max_length=30, unique=True, verbose_name='Заголовок на английском языке')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('short_content_ru', models.TextField(max_length=200, verbose_name='Краткое содержание на русском языке')),
                ('short_content_en', models.TextField(max_length=200, verbose_name='Краткое содержание на английском языке')),
                ('_content_ru_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_ru', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Содержание на русском языке')),
                ('_content_en_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_en', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Содержание на английском языке')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=20)),
                ('image', models.ImageField(error_messages={'empty': 'Выгружаемый файл пуст', 'invalid_image': 'Данный формат изображения не поддерживается сайтом', 'required': 'Укажите файл изображения'}, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
