# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=40, verbose_name='Название на русском языке')),
                ('name_en', models.CharField(max_length=40, verbose_name='Название на английском языке')),
                ('description_ru', models.TextField(verbose_name='Описание на русском языке')),
                ('description_en', models.TextField(verbose_name='Описание на английском языке')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(error_messages={'empty': 'Выгружаемый файл пуст', 'invalid_image': 'Данный формат изображения не поддерживается сайтом', 'required': 'Укажите файл изображения'}, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
