# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(error_messages={'empty': 'Выгружаемый файл пуст', 'invalid_image': 'Данный формат изображения не поддерживается сайтом', 'required': 'Укажите файл изображения'}, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
