# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Название на русском языке')),
                ('title_en', models.CharField(max_length=30, verbose_name='Название на английском языке')),
                ('img_key', models.SlugField(blank=True, max_length=10, null=True)),
                ('key', models.SlugField(default='', max_length=10)),
                ('description_ru', models.TextField(verbose_name='Краткое описание на русском языке')),
                ('description_en', models.TextField(verbose_name='Краткое описание на английском языке')),
                ('_content_ru_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_ru', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Полное описание на русском языке')),
                ('_content_en_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_en', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Полное описание на английском языке')),
                ('src', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название на русском языке')),
                ('name_en', models.CharField(max_length=50, verbose_name='Название на английском языке')),
                ('_content_ru_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_ru', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Содержание на русском языке')),
                ('_content_en_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content_en', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Содержание на английском языке')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.Industry', verbose_name='Отрасль')),
            ],
        ),
    ]
