# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:38
from __future__ import unicode_literals

from django.db import migrations
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='content_en',
            field=precise_bbcode.fields.BBCodeTextField(max_length=500, no_rendered_field=True, verbose_name='Полное описание на английском языке'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='content_ru',
            field=precise_bbcode.fields.BBCodeTextField(max_length=500, no_rendered_field=True, verbose_name='Полное описание на русском языке'),
        ),
    ]
