# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20160727_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_en',
            field=models.TextField(verbose_name='Название на английском языке'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_ru',
            field=models.TextField(verbose_name='Название на русском языке'),
        ),
    ]
