# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20160729_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=250, verbose_name='Название на английском языке'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=250, verbose_name='Название на русском языке'),
        ),
    ]
