# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Заголовок')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('short_content', models.TextField(max_length=200, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsch')], max_length=20)),
                ('image', models.ImageField(error_messages={'empty': 'Выгружаемый файл пуст', 'invalid_image': 'Данный формат изображения не поддерживается сайтом', 'required': 'Укажите файл изображения'}, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
